from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image as RLImage, Table
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import inch
from datetime import datetime

def generate_individual_report(result, output_path="Patch_Report.pdf"):
    styles = getSampleStyleSheet()
    doc = SimpleDocTemplate(output_path, pagesize=A4)
    elements = []

    elements.append(Paragraph("<b>Patch-Level Cancer Detection</b>", styles["Title"]))
    elements.append(Paragraph(f"Generated by: <b>Zohaib Shaikh</b>", styles["Normal"]))
    elements.append(Paragraph(f"Role: <b>AI/ML Engineer</b>", styles["Normal"]))
    elements.append(Paragraph(f"Organization: <b>McAttoh</b>", styles["Normal"]))
    elements.append(Paragraph(f"Date: {datetime.now().strftime('%Y-%m-%d')}", styles["Normal"]))
    elements.append(Spacer(1, 24))

    row = [
        RLImage(result["original"], width=2.5 * inch, height=2.5 * inch),
        RLImage(result["overlay"], width=2.5 * inch, height=2.5 * inch)
    ]
    elements.append(Table([row]))
    elements.append(Spacer(1, 12))

    elements.append(Paragraph(f"<b>Prediction:</b> {'Abnormal' if result['pred'] else 'Normal'}", styles["Normal"]))
    elements.append(Paragraph(f"<b>Confidence:</b> {result['conf'] * 100:.2f}%", styles["Normal"]))
    elements.append(Paragraph(f"<b>AI Observation:</b> {result['interpretation']}", styles["Normal"]))
    elements.append(Paragraph(f"<b>Clinical Note:</b> {result['recommendation']}", styles["Normal"]))
    elements.append(Paragraph(f"<b>Focus Center:</b> {result['center']}", styles["Normal"]))
    elements.append(Paragraph(f"<b>Focus Area:</b> {result['focus_percent']:.2f}%", styles["Normal"]))

    doc.build(elements)
    return output_path
